# Generated by Django 5.0.1 on 2024-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresumedetails',
            name='certification',
            field=models.ManyToManyField(blank=True, null=True, to='register.certification'),
        ),
        migrations.AlterField(
            model_name='userresumedetails',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='register.experience'),
        ),
        migrations.AlterField(
            model_name='userresumedetails',
            name='miniproject',
            field=models.ManyToManyField(blank=True, null=True, to='register.miniprojects'),
        ),
        migrations.AlterField(
            model_name='userresumedetails',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='register.project'),
        ),
        migrations.AlterField(
            model_name='userresumedetails',
            name='strength',
            field=models.ManyToManyField(blank=True, null=True, to='register.strength'),
        ),
    ]
