# Generated by Django 5.0.1 on 2024-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_userresumedetails_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresumedetails',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
