# Generated by Django 5.0.1 on 2024-09-11 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_userresumedetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresumedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresumedetails',
            name='name',
            field=models.TextField(default='resume'),
        ),
        migrations.AddField(
            model_name='userresumedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
