# Generated by Django 5.0.1 on 2024-09-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_colourscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresumedetails',
            name='colorscheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.colourscheme'),
        ),
        migrations.AddField(
            model_name='userresumedetails',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.template'),
        ),
    ]
