# Generated by Django 4.2.11 on 2024-11-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_socialmedia_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
    ]
