# Generated by Django 4.2.11 on 2024-12-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresumedetails',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='userresumedetails',
            name='colorscheme',
        ),
        migrations.DeleteModel(
            name='ColourScheme',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
