# Generated by Django 4.2.11 on 2024-12-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_address_unique_together_alter_address_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_html',
            field=models.TextField(default='template1.html'),
        ),
    ]
