# Generated by Django 4.2.11 on 2024-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_template_template_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_html',
            field=models.TextField(unique=True),
        ),
    ]
